// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmK1RzWObY5st0EUDYBsjvNdpIG3wKf7I',
    appId: '1:923860727032:web:677f7b0cc33480571bf70d',
    messagingSenderId: '923860727032',
    projectId: 'paymate-d9aab',
    authDomain: 'paymate-d9aab.firebaseapp.com',
    storageBucket: 'paymate-d9aab.appspot.com',
    measurementId: 'G-8KZ8MXDXCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJH7_WWlJQ27A1RyrVjgCoM1U8CkPC50g',
    appId: '1:923860727032:android:4296ca430f9284881bf70d',
    messagingSenderId: '923860727032',
    projectId: 'paymate-d9aab',
    storageBucket: 'paymate-d9aab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN0Jl9ow4rw3JFFDmRxIgFFOuGkSb-tEk',
    appId: '1:923860727032:ios:9131275cd5b84a0b1bf70d',
    messagingSenderId: '923860727032',
    projectId: 'paymate-d9aab',
    storageBucket: 'paymate-d9aab.appspot.com',
    iosBundleId: 'codedstudios.paymate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN0Jl9ow4rw3JFFDmRxIgFFOuGkSb-tEk',
    appId: '1:923860727032:ios:df22a3d84a03e8141bf70d',
    messagingSenderId: '923860727032',
    projectId: 'paymate-d9aab',
    storageBucket: 'paymate-d9aab.appspot.com',
    iosBundleId: 'codedstudios.paymate.RunnerTests',
  );
}
